server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }

  location /api/auth/ {
    proxy_pass http://auth-service:3001;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /api/agenda/ {
    proxy_pass http://agenda-service:3002;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /api/notifications/ {
    proxy_pass http://notifications-service:3003;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /api/records/ {
    proxy_pass http://records-service:3004;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}

